### ISSUE TITLE
scan directory structure for all other README.md or possibly just all markdown?

### ISSUE THREAD

**Issue by brntbeer** [marksands/markview#4]

**Comment by marksands** [comment]
I don't particularly want to introduce a file navigator, but I'm open to suggestions. Maybe a drop down list of markdown files in the directory?

**Comment by brntbeer** [comment]
yeah, that's basically what i was thinking. I personally have an "ideas" repo with just tons of READMEs. Would be nice to easily navigate them.

**Comment by brntbeer** [comment]
RIP

**Comment by marksands** [comment]
😆
